apiVersion: apps/v1
kind: Deployment
metadata:
  name: devab
  namespace: test
spec:
 replicas: 2
 selector:
  matchLabels:
   env: linux
 template:
  metadata:
   labels:
    env: linux
  spec:
   containers:
    - name: ubuntu
      image: 826316/ansubuntu:latest
